spring:
  servlet:
    multipart:
      max-request-size: 60MB
      max-file-size: 60MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  application:
    name: spring-library-backend
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  devtools:
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  frontend-url: ${FRONTEND_URL}
  jwt-secret: ${JWT_SECRET}
  jwt-expiration:
    milliseconds: 300000 # 5 minutes


amazon:
  s3:
    bucket: spring-library
    region: us-east-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

google:
  drive:
    service-account-key-file: src/main/resources/pet-lombart-32e441cb0ef5.json
    application-name: spring-library
    folder-id: 1_28PbaT9GTY5ikRYOzzDjKDCe36kW2La