spring:
  application:
    name: spring-library-backend
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode:
        always

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
        hibernate:
            format_sql: true
            use_sql_comments: true

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration:
    milliseconds: 3600000 # 1 hour