spring:
  application:
    name: spring-library-backend
  datasource:
    url: jdbc:mariadb://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-life-time: 300000 # 5 minutes
      idle-timeout: 600000 # 10 minutes
      maximum-pool-size: 10
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

app:
  frontend-url: ${FRONTEND_URL}
  jwt-secret: ${JWT_SECRET}
  jwt-expiration:
    milliseconds: 300000 # 5 minutes
