import { useQrCodeStore } from '@/store/use-qrcode-store';
import { useValidate2FA } from '@/features/user/hooks';
import TwoFAComponent from '@/components/two-fa-component';

const Enable2FAModal = () => {
  const { qrCodeUrl } = useQrCodeStore();
  const { handleValidate2FA } = useValidate2FA();

  return (
    <div className="container mx-auto">
      <p className="text-sm font-normal text-gray-700 mb-4">
        To enable two-factor authentication, scan the QR code below with your
        authentication app (e.g., Google Authenticator, Authy).
      </p>
      <div className="flex justify-center items-center mt-10">
        <div className="border-2 rounded-lg p-2 bg-white shadow-md">
          <img src={qrCodeUrl!} alt="qrCoce" />
        </div>
      </div>

      <div className="mt-4 text-center">
        <p className="text-sm font-normal text-gray-700 mb-2">
          After scanning the QR code, enter the code generated by your app to
          complete the setup.
        </p>
        <p className="text-sm font-normal text-gray-700 mb-2">
          If you lose access to your authentication app, you may lose access to
          your account.
        </p>
      </div>

      <TwoFAComponent handleSubmit={handleValidate2FA} />
    </div>
  );
};

export default Enable2FAModal;
